.Dd April 16, 2026
.Dt GSP 1
.Os GSP 4.0
.Sh NAME
.Nm gsp
.Nd HTML-compatible markup language
.Sh SYNOPSIS
.Nm
.Op Fl cd
.Op Fl I Ar dirname
.Op Ar
.Nm
.Fl h
.Sh DESCRIPTION
This manual documents the
.Nm
cli tool.
For documentation regarding the GSP language itself,
see the
.Sx SEE ALSO
section of this manual.
.Pp
.Nm
is a utility to transpile
.Xr gsp 5
formatted documents into valid HTML.
Files provided as command-line arguments are transpiled with the
results written to the standard output.
If no arguments or the special filename
.Sq Pa \-
is provided, then input will be read from the standard input.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Transliterate GSP comments into HTML comments.
The default behaviour is to drop comments.
.It Fl d
Do not automatically generate a doctype declaration at the beginning
of the document.
.It Fl h
Display help information by opening this manual page.
.It Fl I Ar dirname
Add
.Ar dirname
to the macro search path.
By default the macro search path is empty.
.El
.Sh EXIT STATUS
.Ex -std gsp
.Sh EXAMPLES
Compile the files
.Pa head.gsp
and
.Pa tail.gsp
into one HTML document:
.Pp
.Dl $ gsp head.gsp tail.gsp >out.html
.Pp
Use your own document type instead of the HTML5 one:
.Pp
.Dl $ { printf \(aq%s\(aq \(dq$doctype\(dq; gsp -d index.gsp; } >index.html
.Sh SEE ALSO
.Xr gsp 5 ,
.Xr gsp-macros 7
.Sh AUTHORS
.An Thomas Voss Aq Mt mail@thomasvoss.com
