package parser

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/tdewolff/parse/v2"
)

type parserErrorMarker interface {
	isParserError()
}

func (EOFError) isParserError()             {}
func (InvalidEscapeError) isParserError()   {}
func (InvalidSyntaxError) isParserError()   {}
func (VoidHasChildrenError) isParserError() {}

// InvalidSyntaxError indicates that the parser encountered an
// unexpected token or character while evaluating the GSP document.
type InvalidSyntaxError struct {
	Row      int
	Col      int
	Expected string
	Found    string
}

func newInvalidSyntaxError(in *parse.Input, expected, found string) InvalidSyntaxError {
	row, col, _ := parse.Position(bytes.NewReader(in.Bytes()), in.Offset())
	return InvalidSyntaxError{row, col, expected, found}
}

func (e InvalidSyntaxError) Error() string {
	return fmt.Sprintf("%d:%d: syntax error: expected %s but found %s",
		e.Row, e.Col-1, e.Expected, e.Found)
}

// InvalidEscapeError indicates that an invalid escape sequence was
// encountered within a text block or string literal.
type InvalidEscapeError struct {
	Row  int
	Col  int
	Rune rune
}

func newInvalidEscapeError(in *parse.Input, got rune) InvalidEscapeError {
	row, col, _ := parse.Position(bytes.NewReader(in.Bytes()), in.Offset())
	return InvalidEscapeError{row, col, got}
}

func (e InvalidEscapeError) Error() string {
	return fmt.Sprintf("%d:%d: invalid escape sequence: ‘\\%c’",
		e.Row, e.Col-1, e.Rune)
}

// VoidHasChildrenError indicates that an HTML void element (such as
// img or br) was incorrectly given child nodes.
type VoidHasChildrenError struct {
	Row int
	Col int
	Tag string
}

func newVoidHasChildrenError(in *parse.Input, tag string) VoidHasChildrenError {
	row, col, _ := parse.Position(bytes.NewReader(in.Bytes()), in.Offset())
	return VoidHasChildrenError{row, col, tag}
}

func (e VoidHasChildrenError) Error() string {
	return fmt.Sprintf("%d:%d: void element ‘%s’ may not have any child nodes",
		e.Row, e.Col-1, e.Tag)
}

// EOFError indicates that the parser reached the end of the file
// unexpectedly while parsing a construct.
type EOFError struct{}

func (e EOFError) Error() string {
	return "reached end of file while parsing"
}

// IsParserError reports whether the given error is a custom error
// produced by the GSP parser.
//
// This function is useful for properly formatting error diagnostics,
// such as in command-line tools on UNIX systems.  These tools often
// report an error message with the following format:
//
//	filename: error message
//
// However when an error involves a file location, the space is
// typically omitted:
//
//	filename:row:col: error message
//
// As the errors generated by the parser automatically include the
// error location, this function serves as an indication to if such
// tools require a space or not.
func IsParserError(err error) bool {
	var pe parserErrorMarker
	return errors.As(err, &pe)
}
